server:
  port: 8080
  servlet:
    context-path: /mercado-livre

spring:
  application:
    name: mercado-livre

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mercado-livre
    username: root
    password: root
    testWhileIdle: true
    validationQuery: Select 1
    platform: h2-prod
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

mercado-livre:
  jwt:
    secret: A5769&8*JAJ$Xah$dj!qjhAJK454a@1
    expiration: 90000

